# Generated by Django 4.2 on 2023-04-08 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monthly_Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('age', models.BigIntegerField(blank=True)),
                ('adress', models.CharField(blank=True, max_length=150)),
                ('contact_no', models.BigIntegerField(blank=True)),
                ('weight', models.CharField(blank=True, max_length=150)),
                ('height', models.CharField(blank=True, max_length=150)),
                ('em_fullname', models.CharField(blank=True, max_length=150)),
                ('relationship', models.CharField(blank=True, max_length=150)),
                ('em_contactno', models.BigIntegerField(blank=True)),
                ('em_email', models.EmailField(blank=True, max_length=254)),
                ('file', models.FileField(blank=True, upload_to='')),
                ('is_verified', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
