# Generated by Django 4.2 on 2023-04-08 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_monthly_membership'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Monthly_Membership',
            new_name='Monthly',
        ),
    ]
