# Generated by Django 4.2 on 2023-04-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_rename_monthly_membership_monthly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
